name: diffuser_2d_maze_v1
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip
- patchelf
- glew
- mesalib
- glfw
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - cython<3.0.0
    - numpy<1.24.0
    - gym==0.23.1
    - mujoco-py==2.1.2.14
    - matplotlib==3.3.4
    - torch==1.9.1+cu111
    - typed-argument-parser
    - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
    - scikit-image==0.21.0
    - scikit-video
    - gitpython
    - einops
    - ffmpeg-python
    - pillow
    - tqdm
    - pandas
    - wandb
    - flax>=0.3.5
    - jax<=0.2.21
    - ray==2.0.0
    - crcmod
    - google-api-python-client
    - cryptography
    - git+https://github.com/JannerM/doodad.git@janner
    - gdown>=4.6.0